# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.20.0"
backend_packages.add = [
  "pants.backend.python",
  "pants.backend.experimental.python.typecheck.pyright",
]

[anonymous-telemetry]
enabled = true
repo_id = "3B1D361B-E9F1-49A8-B761-03DCC41FD58E"

[source]
root_patterns = ["/helloworld/"]

[python]
interpreter_constraints = ["==3.8.*"]

[pyright]
version = "pyright@1.1.347"